name: app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  algolia_helper_flutter: ^1.1.0
  auto_route: ^8.3.0
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  currency_text_input_formatter: ^2.2.3
  firebase_app_check: ^0.3.0+3
  firebase_app_installations: ^0.3.0+3
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_dynamic_links: ^6.0.3
  firebase_ui_auth: ^1.15.0
  firebase_ui_firestore: ^1.6.4
  firebase_ui_localizations: ^1.12.0
  firebase_ui_oauth_google: ^1.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.3.0
  flutter_localizations:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  graphql_flutter: ^5.2.0-beta.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  pattern_formatter: ^4.0.0
  universal_io: ^2.2.2
  universal_platform: ^1.1.0
  uuid: ^4.4.2
  very_good_analysis: ^6.0.0

dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
