// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBP9lAbpwYucE3mUM08fqmLmpDplgBSfQ',
    appId: '1:496515282497:web:9aa9c1abe343ecdfccb8c0',
    messagingSenderId: '496515282497',
    projectId: 'splittify-f6bee',
    authDomain: 'splittify-f6bee.firebaseapp.com',
    storageBucket: 'splittify-f6bee.appspot.com',
    measurementId: 'G-XXT6TKGPKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1mTOm1YP0pn_xVkUCAIlQNbRuEagQwrM',
    appId: '1:496515282497:android:8283f9045f6e43ecccb8c0',
    messagingSenderId: '496515282497',
    projectId: 'splittify-f6bee',
    storageBucket: 'splittify-f6bee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr5A6nbE-CFrSXer-ABeU5P-AviF0HWnU',
    appId: '1:496515282497:ios:9f378a1c37988768ccb8c0',
    messagingSenderId: '496515282497',
    projectId: 'splittify-f6bee',
    storageBucket: 'splittify-f6bee.appspot.com',
    iosClientId: '496515282497-beh5m990j047ir63sv9hebasqrd98d5n.apps.googleusercontent.com',
    iosBundleId: 'com.splittify.app',
  );

}